get_params <- function(mle_res) {
	if (inherits(mle_res, "try-error")) {
		return(list())
	} else {
		cl <- as.list(attr(mle_res, "call"))
		params <- mle_res$par
		nms <- c("r", "alpha")
		boffset <- 2L
		hasP0 <- ("p0" %in% names(cl)) && cl$p0
		hasCov <- ("xvars" %in% names(cl)) && !is.null(cl$xvars)

		# Check the call to see if p0 is 
		if (hasP0) {
			params[1] <- invlogit(params[1])
			params[-1] <- exp(params[-1])
			boffset <- boffset + 1L
			nms <- c("p0", nms)		
		} else {
			params <- exp(params)			
		}
		if ("ACV" %in% names(cl) && !is.null(cl$ACV)) {
			boffset <- boffset + 1L
			if (hasP0)
				nms <- c(nms[1], "gamma", nms[-1])
			else
				nms <- c("gamma", nms)
		}
		if (hasCov) {
			params <- c(as.list(params[seq(boffset)]), list(params[-seq(boffset)]))
			nms <- c(nms, "beta")
		} else {
			params <- as.list(params)
		}
		names(params) <- nms
		return(params)
	}
}

fit_allids <- function(mle_res, obs_dat, ...) {
	cl <- as.list(attr(mle_res, "call"))
	mlst <- list(yvar = cl$yvar, xvars = cl$xvars, ACV = cl$ACV, p0 = ifelse(is.null(cl$p0), FALSE, cl$p0))
	res <- mapply(fit_oneid, mle_res, obs_dat, MoreArgs = mlst, SIMPLIFY = FALSE)
	res <- rbindlist(res)
	structure(res, call = cl)
}


fit_oneid <- function(mle_res, obs_dat, yvar, xvars = NULL, ACV = NULL, p0 = FALSE) {
	est_params <- get_params(mle_res)
	if (length(est_params)) {
		y <- obs_dat[[yvar]]
		if (is.null(xvars))
			X <- matrix(seq_along(y), ncol = 1)
		else
			X <- as.matrix(obs_dat[, xvars, with = FALSE])
		if (!is.null(ACV))
			ACV <- obs_dat[[ACV]]

		fit <- cdf(est_params, X, ACV)		
		mape <- median(100 * abs(fit / (y + 1e-6) - 1))
		res <- cbind(obs_dat, PredTrialPct = fit, MAPE = mape)
		if (!is.null(est_params$p0))
			res$p0 <- est_params$p0
		if (!is.null(est_params$gamma))
			res$gamma <- est_params$gamma
		res$r <- est_params$r
		res$alpha <- est_params$alpha
		if (!is.null(est_params$beta)) {
			betamat <- tcrossprod(rep(1, nrow(obs_dat)), est_params$beta)
			colnames(betamat) <- xvars
			res <- cbind(res, beta = betamat)
		}
		return(res)
	} else {
		return(data.table())
	}
}

coefs <- function(mle_fit) {
	# Extract coefficients from a data.table generated by fit_allids
	cl <- attr(mle_fit, "call")
	pnms <- grep("^beta\\.", names(mle_fit), value = TRUE)
	pnms <- c("r", "alpha", pnms)
	if ("gamma" %in% names(mle_fit)) pnms <- c("gamma", pnms)
	if ("p0" %in% names(mle_fit)) pnms <- c("p0", pnms)
	coefs <- mle_fit[, lapply(.SD, unique), keyby = UPC, .SDcols = pnms]
	structure(coefs, call = cl)
}

mapes <- function(mle_fit) {
	# Extract mapes from a data.table generated by fit_allids
	cl <- attr(mle_fit, "call")
	mapes <- mle_fit[, list(MAPE = unique(MAPE)), keyby = UPC]
	structure(mapes, call = cl)
}
	
